version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is in database folder
  db:
    build: ./database
    restart: always
    ports:
      - "33060:3306"
